Fix inference-dev script.

diff --git a/scripts/inference-dev b/scripts/inference-dev
--- a/scripts/inference-dev
+++ b/scripts/inference-dev
@@ -31,11 +31,17 @@ jdkPaths="${cfDir}"/jdk/annotated
 
 CFBuild="${langtoolsDir}"/build/classes:"${annoToolsDir}"/scene-lib/bin:"${cfDir}"/dataflow/build:"${cfDir}"/javacutil/build:"${stubparserDir}"/stubparser.jar:"${cfDir}"/framework/build:"${cfDir}"/checker/build
 
-CFIBuild="${cfiDir}/bin"
+CFIBuild="${cfiDir}/build/classes/java/main"
 
-SAT4jJars="${distDir}"/org.ow2.sat4j.core-2.3.4.jar:"${distDir}"/org.ow2.sat4j.maxsat-2.3.4.jar:"${distDir}"/org.ow2.sat4j.pb-2.3.4.jar
+dependenciesJar="${distDir}/dependencies.jar"
 
-classpath=${CFBuild}:${CFIBuild}
+if [ ! -f "${dependenciesJar}" ];
+then
+   echo "Dependencies Jar not found. Run './gradlew dependenciesJar' to build it."
+   exit 1
+fi
+
+classpath=${CFBuild}:${CFIBuild}:${dependencies}
 
 # append system CLASSPATH to -classpath, so that external checker could export their
 # class files in system CLASSPATH, and let InferenceDevelLauncher append them in -classpath
@@ -48,7 +54,7 @@ fi
 
 eval "java" \
      "-DInferenceDevelLauncher.binary=${distDir} " \
-     "-DInferenceDevelLauncher.runtime.cp=${CFBuild}:${CFIBuild} " \
+     "-DInferenceDevelLauncher.runtime.cp=${CFBuild}:${CFIBuild}:${dependenciesJar} " \
      "-DInferenceDevelLauncher.annotated.jdk=${jdkPaths} " \
      "-classpath ${classpath} " \
      "checkers.inference.InferenceDevelLauncher " "$@"
